### PR TITLE
Add a hint for allowed values types

### PR DESCRIPTION
**Pull request by kean**
Cherry-pick of https://github.com/mattpolzin/OpenAPIKit/pull/245 🍒

### CODE REVIEW

**Comment by kean** [comment]
Hmm, I found one caveat with approach:

> Nullable enum
> A nullable enum can be defined as follows:
> 
>     type: string
>     nullable: true  # <---
>     enum:
>       - asc
>       - desc
>       - null        # <--- without quotes, i.e. null not "null"
> Note that null must be explicitly included in the list of enum values. Using nullable: true alone is not enough here.

From  https://swagger.io/docs/specification/data-models/enums/

I don't understand this and I don't not why this limitation is there.

Also, OpenAPI 3.1 is confusing me. They've removed "nullable" and replaced with with type "null". I don't understand the motivation.

**Comment by kean** [comment]
As far as I can tell, almost _nobody_ adds "null" to their enums and just use `nullable`. I've seen thousands of examples of proper optional enums. But ideally it should be addressed somehow. Maybe `StringOrNull` decodable type?

**Comment by mattpolzin** [comment]
Good catch. I think this is what we get if we change it to `[String?]` but it's been a while so I'd have to try it out and see.

**Comment by mattpolzin** [comment]
This should take care of the problem you uncovered: https://github.com/mattpolzin/OpenAPIKit/pull/247/files

**Comment by mattpolzin** [comment]
> You can't do `"["a", null]"`, as far as I know.

Since in JavaScript everything is nullable, this is fine.

**Review by mattpolzin — APPROVED** [review]
Thanks for submitting (again) and catching the null string issue so fast!

**Comment by kean** [comment]
Thanks! I updated to the latest OpenAPIKit version and it now works as expected.

I also just made my tool public - https://github.com/kean/CreateAPI. I hope to release it soon too.

**Comment by mattpolzin** [comment]
> I also just made my tool public

Congrats! I haven't dug in more than the README yet, but that's a _powerful_ sales pitch. Very exciting project!

You absolutely don't need to convince me of anything, but how would you compare your goals for CreateAPI to the execution of the SwagGen project as of now?

**Comment by kean** [comment]
The main difference is execution. I've tried multiple code generators, not just SwagGen. They all produced code that doesn't compile. I tested with the GitHub spec as an input - that's the primary spec I'm optimizing for. That's not hard to beat. But I go way beyond just making sure the code compiles. It has a ton of smarts and will have more.

**Pull request merged**
